// <auto-generated />
using System;
using Ace.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ace.App.Data.Migrations
{
    [DbContext(typeof(AceDbContext))]
    [Migration("20260116182238_AddAircraftTitleToFlightRecord")]
    partial class AddAircraftTitleToFlightRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ace.App.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Reward")
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnlockedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Ace.App.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedFBOId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedPilotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("REAL");

                    b.Property<int?>("CurrentMaintenanceType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomImagePath")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelBurnGalPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelCapacityGal")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyOperatingCost")
                        .HasColumnType("TEXT");

                    b.Property<double>("HoursSinceACheck")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursSinceLastMaintenance")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursSinceTBO")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsOldtimer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastACheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAnnualInspection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastBCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MaintenanceCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxCargoKg")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxRangeNM")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceCeilingFt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalFlightHours")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("Ace.App.Models.AircraftCatalogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CrewCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("REAL");

                    b.Property<string>("CustomImagePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelBurnGalPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelCapacityGal")
                        .HasColumnType("REAL");

                    b.Property<decimal>("HourlyOperatingCost")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOldtimer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxCargoKg")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxRangeNM")
                        .HasColumnType("REAL");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceCeilingFt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AircraftCatalog");
                });

            modelBuilder.Entity("Ace.App.Models.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AchievementRewardMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AircraftDepreciationRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowAllAircraftForFlightPlan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoStartTracking")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CargoLoadFactorPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CargoRatePerKgPerNMLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CargoRatePerKgPerNMMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CargoRatePerKgPerNMMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CargoRatePerKgPerNMSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CargoRatePerKgPerNMVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CateringCostPerPassenger")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CrewCostMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FBOCostFactor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FBORentInternational")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FBORentLocal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FBORentRegional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuelPricePerGallon")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InsuranceRatePercentage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSimConnectEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LandingFeeLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LandingFeeMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LandingFeeMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LandingFeeSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LandingFeeVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastArrivalIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastDailyEarningsDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDepartureIcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFBOBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSelectedAircraftRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LittleNavmapDatabasePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheck100Hour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheck50Hour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheckACheck")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheckAnnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheckBCheck")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheckCCheck")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCheckDCheck")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCostPerHourLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCostPerHourMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCostPerHourMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCostPerHourSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCostPerHourVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<double>("MapCenterLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("MapCenterLongitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("MapLegendExpanded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MapZoomLevel")
                        .HasColumnType("REAL");

                    b.Property<decimal>("NetworkBonusPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldtimerROIMalusPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PassengerLoadFactorPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotBaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotFlightHoursPerDay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankCaptainBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankCaptainHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankChiefPilotBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankChiefPilotHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankJuniorBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankJuniorHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankSeniorBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankSeniorCaptainBonus")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankSeniorCaptainHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PilotRankSeniorHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlayerFlightBonusPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROIPercentLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROIPercentMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROIPercentMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROIPercentSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROIPercentVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerPaxPerNMLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerPaxPerNMMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerPaxPerNMMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerPaxPerNMSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerPaxPerNMVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteSlotLimitInternational")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteSlotLimitLocal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RouteSlotLimitRegional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoutesPerFBOPairLimit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServiceBonusFactorPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostCatering")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostCateringLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostCateringMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostCateringMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostCateringVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostDeIcing")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostDeIcingLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostDeIcingMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostDeIcingMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostDeIcingVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostGroundHandling")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostGroundHandlingLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostGroundHandlingMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostGroundHandlingMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostGroundHandlingVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostHangar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostHangarLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostHangarMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostHangarMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostHangarVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostRefueling")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostRefuelingLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostRefuelingMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostRefuelingMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceCostRefuelingVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAirports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceCTR")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceClassA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceClassB")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceClassC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceClassD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceClassE")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceDanger")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceGlider")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceOther")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceOverlay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceProhibited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowAirspaceRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundAchievementEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundButtonClickEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundFlightCompletedEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundNotificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundTopOfDescentEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoundVolume")
                        .HasColumnType("REAL");

                    b.Property<bool>("SoundWarningEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TerminalCostLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TerminalCostMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TerminalCostMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TerminalCostSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TerminalCostVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TypeRatingCostLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TypeRatingCostMedium")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TypeRatingCostMediumLarge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TypeRatingCostSmall")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TypeRatingCostVeryLarge")
                        .HasColumnType("TEXT");

                    b.Property<double>("WindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("WindowLeft")
                        .HasColumnType("REAL");

                    b.Property<double>("WindowTop")
                        .HasColumnType("REAL");

                    b.Property<double>("WindowWidth")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Ace.App.Models.DailyEarningsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftRegistration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CrewCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepreciationCost")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNM")
                        .HasColumnType("REAL");

                    b.Property<decimal>("FBOCost")
                        .HasColumnType("TEXT");

                    b.Property<double>("FlightHours")
                        .HasColumnType("REAL");

                    b.Property<decimal>("FuelCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InsuranceCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServiceBonusAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyEarningsDetails");
                });

            modelBuilder.Entity("Ace.App.Models.FBO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCateringService")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDeIcingService")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasGroundHandling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHangarService")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRefuelingService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RentedSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunwayLengthFt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TerminalMonthlyCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("TerminalSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FBOs");
                });

            modelBuilder.Entity("Ace.App.Models.FlightRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aircraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceNM")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Earnings")
                        .HasColumnType("TEXT");

                    b.Property<double>("LandingRate")
                        .HasColumnType("REAL");

                    b.Property<int>("LegType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentFlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlannedDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Ace.App.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RepaidDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRepayment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Ace.App.Models.MaintenanceCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FlightHoursAtCheck")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("MaintenanceChecks");
                });

            modelBuilder.Entity("Ace.App.Models.MonthlyBillingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusPay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RentCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServicesCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TerminalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonthlyBillingDetails");
                });

            modelBuilder.Entity("Ace.App.Models.MsfsAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CrewCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CruiseSpeedKts")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstDetected")
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelBurnGalPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelCapacityGal")
                        .HasColumnType("REAL");

                    b.Property<decimal>("HourlyOperatingCost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetected")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxRangeNM")
                        .HasColumnType("REAL");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("MsfsAircraft");
                });

            modelBuilder.Entity("Ace.App.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmployed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryPerMonth")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalDistanceNM")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalFlightHours")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Ace.App.Models.PilotLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PilotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Ace.App.Models.ScheduledRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedAircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationFBOId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginFBOId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScheduledRoutes");
                });

            modelBuilder.Entity("Ace.App.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Ace.App.Models.TypeRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EarnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PilotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("TypeRatings");
                });

            modelBuilder.Entity("Ace.App.Models.MaintenanceCheck", b =>
                {
                    b.HasOne("Ace.App.Models.Aircraft", "Aircraft")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("Ace.App.Models.PilotLicense", b =>
                {
                    b.HasOne("Ace.App.Models.Pilot", "Pilot")
                        .WithMany("Licenses")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Ace.App.Models.TypeRating", b =>
                {
                    b.HasOne("Ace.App.Models.Pilot", "Pilot")
                        .WithMany("TypeRatings")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Ace.App.Models.Aircraft", b =>
                {
                    b.Navigation("MaintenanceHistory");
                });

            modelBuilder.Entity("Ace.App.Models.Pilot", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("TypeRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
